### ISSUE TITLE
Host demo pages on GitHub Pages

### ISSUE THREAD

**Issue by jdreetz** [InteractiveAdvertisingBureau/openvv-html#6]
https://pages.github.com/

**Comment by goosemanjack** [comment]
Enabled Github pages. Pages are hosted from the **gh-pages** branch of this repo.  This contains is a static html file at the moment because that will most likely suit the needs for test pages.

Site location below:
https://interactiveadvertisingbureau.github.io/openvv-html/

If we so desire we may use Jekyl as well, but likely we will want standard HTML files.
https://jekyllrb.com/docs/home/
